apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-chart
  namespace: cluster-config
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: my-chart
      version: '0.3.0'
      sourceRef:
        kind: HelmRepository
        name: acrrepo
      interval: 1m
  releaseName: my-chart
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    replicaCount: 1
    image:
      repository: nginx
      tag: latest
