apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: acrrepo
  namespace: cluster-config
spec:
  interval: 1m0s
  type: oci
  url: oci://fluxworkload.azurecr.io/helm
  provider: azure